name:   "YanHua's 365 Days"
url:    'http://yanhua365.github.io'
author: 'YanHua'

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

safe:     true
pygments: false
markdown: 'kramdown'
timezone: 'Asia/Shanghai'
